# frozen_string_literal: true

source 'http://rubygems.org'

# Ruby 3.x stdlib gems (extracted from core in Ruby 3.0+)
gem 'base64'
gem 'bigdecimal'
gem 'csv'
gem 'logger'
gem 'stringio'

gem 'colored2'
# html_press dependencies (html_press is now vendored in _ruby/lib/html_press.rb)
# terser (modern ES6+ minifier) is used for JS minification
# CSS concatenation via _ruby/jekyll-plugins/css_concatenator.rb (processes @import in site.styl)
# lightningcss-cli (npm package) is used for CSS minification (installed via _node/package.json)
gem 'jekyll'
gem 'terser'
gem 'tilt'
gem 'webrick'

group :jekyll_plugins do
  gem 'jekyll-contentblocks'
  gem 'jekyll-redirect-from'
end
